baseURL = "/"
relativeURLs = true
# uglyURLs = true
languageCode = "en-us"
title = "朱Chu's Blog"
theme = "erblog"
paginate = 7
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    version = "1.0.1"
    description = " "
    author = "Robert Chu"
    portrait = "/img/chuchu.jpg"
    logo = "/img/chuchu-logo.jpg"
    bio = """
        I adept at learning new topics and facing challenges. </br>
        When dealing issues, I have abilities of rational problem solving and effective negotiating.
    """
    zonebio = """
        This is 朱澔然 from Taiwan, or you can call me Robert. </br>
        I love to explore myself and bring positive impacts to the world. </br>
        Therefore, I volunteered in India for two months in 2016 and exchanged in Finland for a semester in 2018. </br>
        it made me an easy-going and adaptive person with broad international horizon. </br>
        As a developer from 2019, I helped Wistron Cooperation design AI inference system and build CICD processes.
        Now, I'm a senior Devops in Aqumon who just is qualified by CKA. </br>
        Look forward doing enthusing things, such as contents making and experiences sharing.
    """

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "post"
    name = "Post"
    url = "/post/"
    weight = 2

[[menu.main]]
   identifier = "zone"
   name = "ME"
   url = "/zone/"
   weight = 1

# [[menu.main]]
#    identifier = "test-devops"
#    name = "Target"
#    url = "/test-devops/"
#    weight = 1

# [[menu.main]]
#    name = "Gallery"
#    url = "/gallery/"
#    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
# series = "series"

[[menu.icon]]
    url = "mailto:robert010256@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://m.youtube.com/channel/UCkjlUCuvlJ4uXXW4vuu3CxQ"
    name = "youtube"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/chubai_viajar/"
    name = "instagram"
    weight = 1

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/hao-jan-c-92b785177"
#    name = "linkedin"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/robertchu1205"
    name = "github"
    weight = 1